-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    mul_ln6 : IN STD_LOGIC_VECTOR (63 downto 0);
    cmp2139 : IN STD_LOGIC_VECTOR (0 downto 0);
    sub104 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (15 downto 0);
    sub107 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln29_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal cmp2139_read_reg_998 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln29_reg_1007 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1011 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1015 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1015_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1015_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal curr_pixel_data_reg_1020 : STD_LOGIC_VECTOR (7 downto 0);
    signal curr_pixel_data_reg_1020_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal curr_pixel_user_reg_1030 : STD_LOGIC_VECTOR (0 downto 0);
    signal curr_pixel_user_reg_1030_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal curr_pixel_user_reg_1030_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_addr_reg_1035 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp41_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp41_reg_1041 : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_addr_reg_1046 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_1052 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_1057 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_1057_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_1057_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pixel_last_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pixel_last_reg_1062 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pixel_last_reg_1062_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pixel_last_reg_1062_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln30_fu_534_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln30_reg_1067 : STD_LOGIC_VECTOR (10 downto 0);
    signal reuse_select42_fu_588_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select42_reg_1114 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select_fu_598_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select_reg_1120 : STD_LOGIC_VECTOR (7 downto 0);
    signal gx_fu_740_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_reg_1128 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_798_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_reg_1135 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln30_fu_465_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln30_1_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal reuse_addr_reg38_fu_130 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg37_fu_134 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal reuse_addr_reg_fu_138 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_142 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal x_fu_146 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal y_fu_150 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln29_1_fu_422_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_154 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln29_fu_402_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_18_fu_158 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_19_fu_162 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_20_fu_166 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_21_fu_170 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_22_fu_174 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_23_fu_178 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local : STD_LOGIC;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local : STD_LOGIC;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local : STD_LOGIC;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local : STD_LOGIC;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local : STD_LOGIC;
    signal sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local : STD_LOGIC;
    signal zext_ln30_1_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln30_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln29_1_fu_416_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln29_fu_408_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_444_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln29_fu_430_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_507_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln29_2_cast_fu_434_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal cmp105_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln30_2_fu_615_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln56_1_fu_679_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_2_fu_682_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln56_fu_686_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_692_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln56_fu_675_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln57_2_fu_710_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln57_fu_714_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln57_1_fu_707_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln55_2_fu_720_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln55_fu_724_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln57_fu_700_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln55_fu_669_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln56_fu_734_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln56_fu_730_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln59_fu_746_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln60_fu_756_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln60_1_fu_760_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln60_fu_764_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_770_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln57_fu_704_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln55_1_fu_672_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln61_fu_782_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln61_fu_778_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln60_1_fu_788_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln60_fu_792_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln60_fu_752_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln55_fu_808_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_814_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln63_fu_822_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal abs_gx_fu_827_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln59_fu_811_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_838_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln64_fu_846_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal abs_gy_fu_851_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln63_fu_834_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln64_fu_858_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_mag_fu_862_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln65_fu_868_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln53_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_pixel_fu_872_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_pixel_2_fu_877_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP_sobel_accel_stream_stream_axis_0_int_ibkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_U : component sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP_sobel_accel_stream_stream_axis_0_int_ibkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_addr_reg_1035,
        ce0 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local,
        we0 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local,
        d0 => reuse_select_fu_598_p3,
        address1 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_address1,
        ce1 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local,
        q1 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_q1);

    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_U : component sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP_sobel_accel_stream_stream_axis_0_int_ibkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_addr_reg_1046,
        ce0 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local,
        we0 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local,
        d0 => curr_pixel_data_reg_1020,
        address1 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_address1,
        ce1 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local,
        q1 => sobel_accel_stream_stream_axis_0_int_int_int_line_buf_q1);

    flow_control_loop_pipe_sequential_init_U : component sobel_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((first_iter_0_reg_1011 = ap_const_lv1_0) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= empty_22_fu_174;
                elsif (((first_iter_0_reg_1011 = ap_const_lv1_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((first_iter_0_reg_1011 = ap_const_lv1_0) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= empty_19_fu_162;
                elsif (((first_iter_0_reg_1011 = ap_const_lv1_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((first_iter_0_reg_1011 = ap_const_lv1_0) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= empty_18_fu_158;
                elsif (((first_iter_0_reg_1011 = ap_const_lv1_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((first_iter_0_reg_1011 = ap_const_lv1_0) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= empty_20_fu_166;
                elsif (((first_iter_0_reg_1011 = ap_const_lv1_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((first_iter_0_reg_1011 = ap_const_lv1_0) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= empty_23_fu_178;
                elsif (((first_iter_0_reg_1011 = ap_const_lv1_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_154 <= ap_const_lv64_0;
                elsif (((icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_154 <= add_ln29_fu_402_p2;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg38_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg38_fu_130 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg38_fu_130 <= zext_ln30_fu_465_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg_fu_138 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_138 <= zext_ln30_fu_465_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg37_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg37_fu_134 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    reuse_reg37_fu_134 <= reuse_select_fu_598_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_142 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
                    reuse_reg_fu_142 <= curr_pixel_data_reg_1020;
                end if;
            end if; 
        end if;
    end process;

    x_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_146 <= ap_const_lv11_0;
                elsif (((icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_146 <= add_ln30_fu_534_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_150 <= ap_const_lv31_0;
                elsif (((icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    y_fu_150 <= select_ln29_1_fu_422_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln30_reg_1067 <= add_ln30_fu_534_p2;
                addr_cmp41_reg_1041 <= addr_cmp41_fu_482_p2;
                addr_cmp_reg_1052 <= addr_cmp_fu_491_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                curr_pixel_data_reg_1020 <= in_stream_TDATA;
                curr_pixel_user_reg_1030 <= in_stream_TUSER;
                first_iter_0_reg_1011 <= first_iter_0_fu_438_p2;
                icmp_ln29_reg_1007 <= icmp_ln29_fu_382_p2;
                icmp_ln53_reg_1057 <= icmp_ln53_fu_517_p2;
                icmp_reg_1015 <= icmp_fu_454_p2;
                out_pixel_last_reg_1062 <= out_pixel_last_fu_528_p2;
                sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_addr_reg_1035 <= zext_ln30_fu_465_p1(11 - 1 downto 0);
                sobel_accel_stream_stream_axis_0_int_int_int_line_buf_addr_reg_1046 <= zext_ln30_fu_465_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                curr_pixel_data_reg_1020_pp0_iter2_reg <= curr_pixel_data_reg_1020;
                curr_pixel_user_reg_1030_pp0_iter2_reg <= curr_pixel_user_reg_1030;
                curr_pixel_user_reg_1030_pp0_iter3_reg <= curr_pixel_user_reg_1030_pp0_iter2_reg;
                gx_reg_1128 <= gx_fu_740_p2;
                gy_reg_1135 <= gy_fu_798_p2;
                icmp_ln53_reg_1057_pp0_iter2_reg <= icmp_ln53_reg_1057;
                icmp_ln53_reg_1057_pp0_iter3_reg <= icmp_ln53_reg_1057_pp0_iter2_reg;
                icmp_reg_1015_pp0_iter2_reg <= icmp_reg_1015;
                icmp_reg_1015_pp0_iter3_reg <= icmp_reg_1015_pp0_iter2_reg;
                out_pixel_last_reg_1062_pp0_iter2_reg <= out_pixel_last_reg_1062;
                out_pixel_last_reg_1062_pp0_iter3_reg <= out_pixel_last_reg_1062_pp0_iter2_reg;
                reuse_select42_reg_1114 <= reuse_select42_fu_588_p3;
                reuse_select_reg_1120 <= reuse_select_fu_598_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
                ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
                ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
                ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
                ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
                ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
                ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
                ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
                ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then
                empty_18_fu_158 <= reuse_select42_fu_588_p3;
                empty_19_fu_162 <= empty_18_fu_158;
                empty_20_fu_166 <= empty_21_fu_170;
                empty_21_fu_170 <= reuse_select_fu_598_p3;
                empty_22_fu_174 <= curr_pixel_data_reg_1020;
                empty_23_fu_178 <= empty_22_fu_174;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln30_1_fu_618_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0) and (cmp2139_read_reg_998 = ap_const_lv1_1))) then
                p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E <= curr_pixel_data_reg_1020;
                p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1 <= reuse_select_fu_598_p3;
                p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2 <= reuse_select42_fu_588_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    abs_gx_fu_827_p3 <= 
        sub_ln63_fu_822_p2 when (tmp_5_fu_814_p3(0) = '1') else 
        gx_reg_1128;
    abs_gy_fu_851_p3 <= 
        sub_ln64_fu_846_p2 when (tmp_6_fu_838_p3(0) = '1') else 
        gy_reg_1135;
    add_ln29_1_fu_416_p2 <= std_logic_vector(unsigned(y_fu_150) + unsigned(ap_const_lv31_1));
    add_ln29_fu_402_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_154) + unsigned(ap_const_lv64_1));
    add_ln30_fu_534_p2 <= std_logic_vector(unsigned(select_ln29_fu_408_p3) + unsigned(ap_const_lv11_1));
    add_ln56_fu_734_p2 <= std_logic_vector(signed(sext_ln57_fu_700_p1) + signed(zext_ln55_fu_669_p1));
    add_ln57_fu_714_p2 <= std_logic_vector(unsigned(zext_ln56_fu_675_p1) + unsigned(zext_ln57_2_fu_710_p1));
    add_ln60_fu_792_p2 <= std_logic_vector(signed(sext_ln61_fu_778_p1) + signed(sext_ln60_1_fu_788_p1));
    addr_cmp41_fu_482_p2 <= "1" when (reuse_addr_reg38_fu_130 = zext_ln30_fu_465_p1) else "0";
    addr_cmp_fu_491_p2 <= "1" when (reuse_addr_reg_fu_138 = zext_ln30_fu_465_p1) else "0";
    and_ln53_fu_804_p2 <= (icmp_reg_1015_pp0_iter3_reg and icmp_ln53_reg_1057_pp0_iter3_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_block_state2_pp0_stage0_iter1, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_block_state2_pp0_stage0_iter1, out_stream_TREADY, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((out_stream_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_block_state2_pp0_stage0_iter1, out_stream_TREADY, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((out_stream_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(in_stream_TVALID, icmp_ln29_fu_382_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln29_fu_382_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln29_fu_382_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln29_reg_1007)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= "XXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cmp105_fu_460_p2 <= "1" when (zext_ln29_fu_430_p1 = sub104) else "0";
    cmp2139_read_reg_998 <= cmp2139;
    first_iter_0_fu_438_p2 <= "1" when (select_ln29_fu_408_p3 = ap_const_lv11_0) else "0";
    gx_fu_740_p2 <= std_logic_vector(unsigned(add_ln56_fu_734_p2) + unsigned(sext_ln56_fu_730_p1));
    gy_fu_798_p2 <= std_logic_vector(unsigned(add_ln60_fu_792_p2) + unsigned(sext_ln60_fu_752_p1));
    icmp_fu_454_p2 <= "0" when (tmp_3_fu_444_p4 = ap_const_lv30_0) else "1";
    icmp_ln29_fu_382_p2 <= "1" when (indvar_flatten_fu_154 = mul_ln6) else "0";
    icmp_ln30_1_fu_618_p2 <= "1" when (signed(zext_ln30_2_fu_615_p1) < signed(width)) else "0";
    icmp_ln30_fu_397_p2 <= "1" when (signed(zext_ln30_1_fu_393_p1) < signed(width)) else "0";
    icmp_ln53_fu_517_p2 <= "0" when (tmp_4_fu_507_p4 = ap_const_lv10_0) else "1";
    icmp_ln82_fu_523_p2 <= "1" when (select_ln29_2_cast_fu_434_p1 = sub107) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, in_stream_TVALID, icmp_ln29_fu_382_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln29_fu_382_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_fu_382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    out_pixel_last_fu_528_p2 <= (icmp_ln82_fu_523_p2 and cmp105_fu_460_p2);
    out_stream_TDATA <= 
        ap_const_lv8_FF when (output_pixel_2_fu_877_p2(0) = '1') else 
        ap_const_lv8_0;

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDEST <= "X";
    out_stream_TID <= "X";
    out_stream_TKEEP <= ap_const_lv1_1;
    out_stream_TLAST <= out_pixel_last_reg_1062_pp0_iter3_reg;
    out_stream_TSTRB <= ap_const_lv1_1;
    out_stream_TUSER <= curr_pixel_user_reg_1030_pp0_iter3_reg;

    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    output_pixel_2_fu_877_p2 <= (output_pixel_fu_872_p2 and and_ln53_fu_804_p2);
    output_pixel_fu_872_p2 <= "1" when (unsigned(sext_ln65_fu_868_p1) > unsigned(empty)) else "0";
    reuse_select42_fu_588_p3 <= 
        reuse_reg37_fu_134 when (addr_cmp41_reg_1041(0) = '1') else 
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_q1;
    reuse_select_fu_598_p3 <= 
        reuse_reg_fu_142 when (addr_cmp_reg_1052(0) = '1') else 
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_q1;
    select_ln29_1_fu_422_p3 <= 
        y_fu_150 when (icmp_ln30_fu_397_p2(0) = '1') else 
        add_ln29_1_fu_416_p2;
    select_ln29_2_cast_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln29_fu_408_p3),32));
    select_ln29_fu_408_p3 <= 
        x_fu_146 when (icmp_ln30_fu_397_p2(0) = '1') else 
        ap_const_lv11_0;
        sext_ln55_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gx_reg_1128),16));

        sext_ln56_fu_730_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln55_fu_724_p2),11));

        sext_ln57_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_692_p3),11));

        sext_ln59_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_reg_1135),16));

        sext_ln60_1_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln61_fu_782_p2),11));

        sext_ln60_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln59_fu_746_p2),11));

        sext_ln61_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_770_p3),11));

        sext_ln63_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_gx_fu_827_p3),12));

        sext_ln64_fu_858_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_gy_fu_851_p3),12));

        sext_ln65_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_mag_fu_862_p2),16));

    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_address1 <= zext_ln30_fu_465_p1(11 - 1 downto 0);

    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local <= ap_const_logic_1;
        else 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local <= ap_const_logic_1;
        else 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln29_reg_1007)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local <= ap_const_logic_1;
        else 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_address1 <= zext_ln30_fu_465_p1(11 - 1 downto 0);

    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local <= ap_const_logic_1;
        else 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local <= ap_const_logic_1;
        else 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln29_reg_1007)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_1007 = ap_const_lv1_0))) then 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local <= ap_const_logic_1;
        else 
            sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln55_fu_724_p2 <= std_logic_vector(unsigned(zext_ln57_1_fu_707_p1) - unsigned(zext_ln55_2_fu_720_p1));
    sub_ln56_fu_686_p2 <= std_logic_vector(unsigned(zext_ln56_1_fu_679_p1) - unsigned(zext_ln56_2_fu_682_p1));
    sub_ln59_fu_746_p2 <= std_logic_vector(unsigned(zext_ln57_2_fu_710_p1) - unsigned(zext_ln56_fu_675_p1));
    sub_ln60_fu_764_p2 <= std_logic_vector(unsigned(zext_ln60_fu_756_p1) - unsigned(zext_ln60_1_fu_760_p1));
    sub_ln61_fu_782_p2 <= std_logic_vector(unsigned(zext_ln57_fu_704_p1) - unsigned(zext_ln55_1_fu_672_p1));
    sub_ln63_fu_822_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gx_reg_1128));
    sub_ln64_fu_846_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gy_reg_1135));
    sum_mag_fu_862_p2 <= std_logic_vector(signed(sext_ln63_fu_834_p1) + signed(sext_ln64_fu_858_p1));
    tmp_1_fu_770_p3 <= (sub_ln60_fu_764_p2 & ap_const_lv1_0);
    tmp_3_fu_444_p4 <= select_ln29_1_fu_422_p3(30 downto 1);
    tmp_4_fu_507_p4 <= select_ln29_fu_408_p3(10 downto 1);
    tmp_5_fu_814_p3 <= sext_ln55_fu_808_p1(15 downto 15);
    tmp_6_fu_838_p3 <= sext_ln59_fu_811_p1(15 downto 15);
    tmp_fu_692_p3 <= (sub_ln56_fu_686_p2 & ap_const_lv1_0);
    zext_ln29_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln29_1_fu_422_p3),32));
    zext_ln30_1_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_146),32));
    zext_ln30_2_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln30_reg_1067),32));
    zext_ln30_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln29_fu_408_p3),64));
    zext_ln55_1_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select42_reg_1114),9));
    zext_ln55_2_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_fu_714_p2),10));
    zext_ln55_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select42_reg_1114),11));
    zext_ln56_1_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select_reg_1120),9));
    zext_ln56_2_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317),9));
    zext_ln56_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299),9));
    zext_ln57_1_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(curr_pixel_data_reg_1020_pp0_iter2_reg),10));
    zext_ln57_2_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326),9));
    zext_ln57_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(curr_pixel_data_reg_1020_pp0_iter2_reg),9));
    zext_ln60_1_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308),9));
    zext_ln60_fu_756_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335),9));
end behav;
