#include "sobel_accel.h"
#include <iostream>
#include <fstream>
#include <iomanip>

int main() {
    int width = 64;
    int height = 64;
    int threshold = 100;

    // 1. Instantiate AXI-Streams
    hls::stream<pixel_data> in_stream("in_stream");
    hls::stream<pixel_data> out_stream("out_stream");

    // 2. Open Golden Model files (generated by your Python script)
    // 注意：路径里的斜杠必须用正斜杠 '/'，或者双反斜杠 '\\'
    std::ifstream fin("F:/nyuhomework/hardware/project/action/hls/tb_input_pixels.txt");
    std::ifstream fgolden("F:/nyuhomework/hardware/project/action/hls/tb_output_edge.txt");
    std::ofstream fout("hls_output.txt");

    if (!fin.is_open() || !fgolden.is_open()) {
        std::cerr << "Error: Cannot open test vector files!" << std::endl;
        return 1;
    }

    // 3. Read input file and push to AXI-Stream
    int pixel_val;
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            fin >> std::hex >> pixel_val; // Read hex format

            pixel_data p;
            p.data = pixel_val;
            p.keep = 1;
            p.strb = 1;
            p.user = (y == 0 && x == 0) ? 1 : 0; // Start of Frame (TUSER)
            p.last = (x == width - 1) ? 1 : 0;   // End of Line (TLAST)

            in_stream.write(p);
        }
    }

    // 4. Run the Hardware Accelerator
    std::cout << "Running Sobel Accelerator..." << std::endl;
    sobel_accel(in_stream, out_stream, width, height, threshold);

    // 5. Read output stream, save, and compare with Golden Model
    int errors = 0;
    int expected_val;
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            pixel_data out_p = out_stream.read();
            fgolden >> std::hex >> expected_val;

            // Write HLS output to file
            fout << std::hex << std::setw(2) << std::setfill('0')
                 << (int)out_p.data << std::endl;

            // Compare
            if (out_p.data != expected_val) {
                if (errors < 10) { // Print first 10 errors
                    std::cerr << "Mismatch at (x=" << x << ", y=" << y << "): "
                              << "Expected " << expected_val << ", Got "
                              << (int)out_p.data << std::endl;
                }
                errors++;
            }
        }
    }

    // 6. Print Final Result
    if (errors == 0) {
        std::cout << "TEST PASSED! 100% Bit-true match with Golden Model." << std::endl;
        return 0; // Return 0 means success
    } else {
        std::cout << "TEST FAILED! Total errors: " << errors << std::endl;
        return 1; // Return non-zero means failure
    }
}
