// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        mul_ln6,
        cmp2139,
        sub104,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        empty,
        sub107,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        width
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [63:0] mul_ln6;
input  [0:0] cmp2139;
input  [31:0] sub104;
input  [7:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
input  [15:0] empty;
input  [31:0] sub107;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input  [31:0] width;

reg ap_idle;
reg in_stream_TREADY;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln29_fu_382_p2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [10:0] sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_address1;
wire   [7:0] sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_q1;
wire   [10:0] sobel_accel_stream_stream_axis_0_int_int_int_line_buf_address1;
wire   [7:0] sobel_accel_stream_stream_axis_0_int_int_int_line_buf_q1;
reg   [7:0] p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2;
reg   [7:0] p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1;
reg   [7:0] p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] cmp2139_read_reg_998;
reg   [0:0] icmp_ln29_reg_1007;
wire   [0:0] first_iter_0_fu_438_p2;
reg   [0:0] first_iter_0_reg_1011;
wire   [0:0] icmp_fu_454_p2;
reg   [0:0] icmp_reg_1015;
reg   [0:0] icmp_reg_1015_pp0_iter2_reg;
reg   [0:0] icmp_reg_1015_pp0_iter3_reg;
reg   [7:0] curr_pixel_data_reg_1020;
reg   [7:0] curr_pixel_data_reg_1020_pp0_iter2_reg;
reg   [0:0] curr_pixel_user_reg_1030;
reg   [0:0] curr_pixel_user_reg_1030_pp0_iter2_reg;
reg   [0:0] curr_pixel_user_reg_1030_pp0_iter3_reg;
reg   [10:0] sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_addr_reg_1035;
wire   [0:0] addr_cmp41_fu_482_p2;
reg   [0:0] addr_cmp41_reg_1041;
reg   [10:0] sobel_accel_stream_stream_axis_0_int_int_int_line_buf_addr_reg_1046;
wire   [0:0] addr_cmp_fu_491_p2;
reg   [0:0] addr_cmp_reg_1052;
wire   [0:0] icmp_ln53_fu_517_p2;
reg   [0:0] icmp_ln53_reg_1057;
reg   [0:0] icmp_ln53_reg_1057_pp0_iter2_reg;
reg   [0:0] icmp_ln53_reg_1057_pp0_iter3_reg;
wire   [0:0] out_pixel_last_fu_528_p2;
reg   [0:0] out_pixel_last_reg_1062;
reg   [0:0] out_pixel_last_reg_1062_pp0_iter2_reg;
reg   [0:0] out_pixel_last_reg_1062_pp0_iter3_reg;
wire   [10:0] add_ln30_fu_534_p2;
reg   [10:0] add_ln30_reg_1067;
wire   [7:0] reuse_select42_fu_588_p3;
reg   [7:0] reuse_select42_reg_1114;
wire   [7:0] reuse_select_fu_598_p3;
reg   [7:0] reuse_select_reg_1120;
wire  signed [10:0] gx_fu_740_p2;
reg  signed [10:0] gx_reg_1128;
wire  signed [10:0] gy_fu_798_p2;
reg  signed [10:0] gy_reg_1135;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [7:0] ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
reg   [7:0] ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
reg   [7:0] ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
reg   [7:0] ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
wire   [7:0] ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
reg   [7:0] ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
reg   [7:0] ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
reg   [7:0] ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
wire   [7:0] ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
reg   [7:0] ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
reg   [7:0] ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
reg   [7:0] ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
wire   [7:0] ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
reg   [7:0] ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
reg   [7:0] ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
reg   [7:0] ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
wire   [7:0] ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
reg   [7:0] ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
reg   [7:0] ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
reg   [7:0] ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
wire   [63:0] zext_ln30_fu_465_p1;
wire   [0:0] icmp_ln30_1_fu_618_p2;
reg   [63:0] reuse_addr_reg38_fu_130;
wire    ap_loop_init;
reg   [7:0] reuse_reg37_fu_134;
reg   [63:0] reuse_addr_reg_fu_138;
reg   [7:0] reuse_reg_fu_142;
reg   [10:0] x_fu_146;
reg   [30:0] y_fu_150;
wire   [30:0] select_ln29_1_fu_422_p3;
reg   [63:0] indvar_flatten_fu_154;
wire   [63:0] add_ln29_fu_402_p2;
reg   [7:0] empty_18_fu_158;
reg   [7:0] empty_19_fu_162;
reg   [7:0] empty_20_fu_166;
reg   [7:0] empty_21_fu_170;
reg   [7:0] empty_22_fu_174;
reg   [7:0] empty_23_fu_178;
reg    ap_block_pp0_stage0_01001;
reg    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local;
reg    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local;
reg    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local;
reg    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local;
reg    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local;
reg    sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local;
wire   [31:0] zext_ln30_1_fu_393_p1;
wire   [0:0] icmp_ln30_fu_397_p2;
wire   [30:0] add_ln29_1_fu_416_p2;
wire   [10:0] select_ln29_fu_408_p3;
wire   [29:0] tmp_3_fu_444_p4;
wire   [31:0] zext_ln29_fu_430_p1;
wire   [9:0] tmp_4_fu_507_p4;
wire   [31:0] select_ln29_2_cast_fu_434_p1;
wire   [0:0] cmp105_fu_460_p2;
wire   [0:0] icmp_ln82_fu_523_p2;
wire   [31:0] zext_ln30_2_fu_615_p1;
wire   [8:0] zext_ln56_1_fu_679_p1;
wire   [8:0] zext_ln56_2_fu_682_p1;
wire   [8:0] sub_ln56_fu_686_p2;
wire   [9:0] tmp_fu_692_p3;
wire   [8:0] zext_ln56_fu_675_p1;
wire   [8:0] zext_ln57_2_fu_710_p1;
wire   [8:0] add_ln57_fu_714_p2;
wire   [9:0] zext_ln57_1_fu_707_p1;
wire   [9:0] zext_ln55_2_fu_720_p1;
wire   [9:0] sub_ln55_fu_724_p2;
wire  signed [10:0] sext_ln57_fu_700_p1;
wire   [10:0] zext_ln55_fu_669_p1;
wire   [10:0] add_ln56_fu_734_p2;
wire  signed [10:0] sext_ln56_fu_730_p1;
wire   [8:0] sub_ln59_fu_746_p2;
wire   [8:0] zext_ln60_fu_756_p1;
wire   [8:0] zext_ln60_1_fu_760_p1;
wire   [8:0] sub_ln60_fu_764_p2;
wire   [9:0] tmp_1_fu_770_p3;
wire   [8:0] zext_ln57_fu_704_p1;
wire   [8:0] zext_ln55_1_fu_672_p1;
wire   [8:0] sub_ln61_fu_782_p2;
wire  signed [10:0] sext_ln61_fu_778_p1;
wire  signed [10:0] sext_ln60_1_fu_788_p1;
wire   [10:0] add_ln60_fu_792_p2;
wire  signed [10:0] sext_ln60_fu_752_p1;
wire  signed [15:0] sext_ln55_fu_808_p1;
wire   [0:0] tmp_5_fu_814_p3;
wire   [10:0] sub_ln63_fu_822_p2;
wire   [10:0] abs_gx_fu_827_p3;
wire  signed [15:0] sext_ln59_fu_811_p1;
wire   [0:0] tmp_6_fu_838_p3;
wire   [10:0] sub_ln64_fu_846_p2;
wire   [10:0] abs_gy_fu_851_p3;
wire  signed [11:0] sext_ln63_fu_834_p1;
wire  signed [11:0] sext_ln64_fu_858_p1;
wire   [11:0] sum_mag_fu_862_p2;
wire  signed [15:0] sext_ln65_fu_868_p1;
wire   [0:0] and_ln53_fu_804_p2;
wire   [0:0] output_pixel_fu_872_p2;
wire   [0:0] output_pixel_2_fu_877_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2 = 8'd0;
#0 p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1 = 8'd0;
#0 p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E = 8'd0;
#0 reuse_addr_reg38_fu_130 = 64'd0;
#0 reuse_reg37_fu_134 = 8'd0;
#0 reuse_addr_reg_fu_138 = 64'd0;
#0 reuse_reg_fu_142 = 8'd0;
#0 x_fu_146 = 11'd0;
#0 y_fu_150 = 31'd0;
#0 indvar_flatten_fu_154 = 64'd0;
#0 empty_18_fu_158 = 8'd0;
#0 empty_19_fu_162 = 8'd0;
#0 empty_20_fu_166 = 8'd0;
#0 empty_21_fu_170 = 8'd0;
#0 empty_22_fu_174 = 8'd0;
#0 empty_23_fu_178 = 8'd0;
#0 ap_done_reg = 1'b0;
end

sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP_sobel_accel_stream_stream_axis_0_int_ibkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_addr_reg_1035),
    .ce0(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local),
    .we0(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local),
    .d0(reuse_select_fu_598_p3),
    .address1(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_address1),
    .ce1(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local),
    .q1(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_q1)
);

sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP_sobel_accel_stream_stream_axis_0_int_ibkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
sobel_accel_stream_stream_axis_0_int_int_int_line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_addr_reg_1046),
    .ce0(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local),
    .we0(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local),
    .d0(curr_pixel_data_reg_1020),
    .address1(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_address1),
    .ce1(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local),
    .q1(sobel_accel_stream_stream_axis_0_int_int_int_line_buf_q1)
);

sobel_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((first_iter_0_reg_1011 == 1'd0) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= empty_22_fu_174;
        end else if (((first_iter_0_reg_1011 == 1'd1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((first_iter_0_reg_1011 == 1'd0) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= empty_19_fu_162;
        end else if (((first_iter_0_reg_1011 == 1'd1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((first_iter_0_reg_1011 == 1'd0) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= empty_18_fu_158;
        end else if (((first_iter_0_reg_1011 == 1'd1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((first_iter_0_reg_1011 == 1'd0) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= empty_20_fu_166;
        end else if (((first_iter_0_reg_1011 == 1'd1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((first_iter_0_reg_1011 == 1'd0) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= empty_23_fu_178;
        end else if (((first_iter_0_reg_1011 == 1'd1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_154 <= 64'd0;
        end else if (((icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_154 <= add_ln29_fu_402_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg38_fu_130 <= 64'd18446744073709551615;
        end else if (((icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg38_fu_130 <= zext_ln30_fu_465_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg_fu_138 <= 64'd18446744073709551615;
        end else if (((icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg_fu_138 <= zext_ln30_fu_465_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg37_fu_134 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            reuse_reg37_fu_134 <= reuse_select_fu_598_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_142 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd0))) begin
            reuse_reg_fu_142 <= curr_pixel_data_reg_1020;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_146 <= 11'd0;
        end else if (((icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_fu_146 <= add_ln30_fu_534_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_150 <= 31'd0;
        end else if (((icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            y_fu_150 <= select_ln29_1_fu_422_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln30_reg_1067 <= add_ln30_fu_534_p2;
        addr_cmp41_reg_1041 <= addr_cmp41_fu_482_p2;
        addr_cmp_reg_1052 <= addr_cmp_fu_491_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        curr_pixel_data_reg_1020 <= in_stream_TDATA;
        curr_pixel_user_reg_1030 <= in_stream_TUSER;
        first_iter_0_reg_1011 <= first_iter_0_fu_438_p2;
        icmp_ln29_reg_1007 <= icmp_ln29_fu_382_p2;
        icmp_ln53_reg_1057 <= icmp_ln53_fu_517_p2;
        icmp_reg_1015 <= icmp_fu_454_p2;
        out_pixel_last_reg_1062 <= out_pixel_last_fu_528_p2;
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_addr_reg_1035 <= zext_ln30_fu_465_p1;
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_addr_reg_1046 <= zext_ln30_fu_465_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        curr_pixel_data_reg_1020_pp0_iter2_reg <= curr_pixel_data_reg_1020;
        curr_pixel_user_reg_1030_pp0_iter2_reg <= curr_pixel_user_reg_1030;
        curr_pixel_user_reg_1030_pp0_iter3_reg <= curr_pixel_user_reg_1030_pp0_iter2_reg;
        gx_reg_1128 <= gx_fu_740_p2;
        gy_reg_1135 <= gy_fu_798_p2;
        icmp_ln53_reg_1057_pp0_iter2_reg <= icmp_ln53_reg_1057;
        icmp_ln53_reg_1057_pp0_iter3_reg <= icmp_ln53_reg_1057_pp0_iter2_reg;
        icmp_reg_1015_pp0_iter2_reg <= icmp_reg_1015;
        icmp_reg_1015_pp0_iter3_reg <= icmp_reg_1015_pp0_iter2_reg;
        out_pixel_last_reg_1062_pp0_iter2_reg <= out_pixel_last_reg_1062;
        out_pixel_last_reg_1062_pp0_iter3_reg <= out_pixel_last_reg_1062_pp0_iter2_reg;
        reuse_select42_reg_1114 <= reuse_select42_fu_588_p3;
        reuse_select_reg_1120 <= reuse_select_fu_598_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
        ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
        ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
        ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
        ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;
        ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;
        ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;
        ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;
        ap_phi_reg_pp0_iter2_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 <= ap_phi_reg_pp0_iter1_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd0))) begin
        empty_18_fu_158 <= reuse_select42_fu_588_p3;
        empty_19_fu_162 <= empty_18_fu_158;
        empty_20_fu_166 <= empty_21_fu_170;
        empty_21_fu_170 <= reuse_select_fu_598_p3;
        empty_22_fu_174 <= curr_pixel_data_reg_1020;
        empty_23_fu_178 <= empty_22_fu_174;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_1_fu_618_p2 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd0) & (cmp2139_read_reg_998 == 1'd1))) begin
        p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E <= curr_pixel_data_reg_1020;
        p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_1 <= reuse_select_fu_598_p3;
        p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_2 <= reuse_select42_fu_588_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln29_fu_382_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_fu_382_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local = 1'b1;
    end else begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local = 1'b1;
    end else begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd0))) begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local = 1'b1;
    end else begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local = 1'b1;
    end else begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local = 1'b1;
    end else begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_1007 == 1'd0))) begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local = 1'b1;
    end else begin
        sobel_accel_stream_stream_axis_0_int_int_int_line_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_gx_fu_827_p3 = ((tmp_5_fu_814_p3[0:0] == 1'b1) ? sub_ln63_fu_822_p2 : gx_reg_1128);

assign abs_gy_fu_851_p3 = ((tmp_6_fu_838_p3[0:0] == 1'b1) ? sub_ln64_fu_846_p2 : gy_reg_1135);

assign add_ln29_1_fu_416_p2 = (y_fu_150 + 31'd1);

assign add_ln29_fu_402_p2 = (indvar_flatten_fu_154 + 64'd1);

assign add_ln30_fu_534_p2 = (select_ln29_fu_408_p3 + 11'd1);

assign add_ln56_fu_734_p2 = ($signed(sext_ln57_fu_700_p1) + $signed(zext_ln55_fu_669_p1));

assign add_ln57_fu_714_p2 = (zext_ln56_fu_675_p1 + zext_ln57_2_fu_710_p1);

assign add_ln60_fu_792_p2 = ($signed(sext_ln61_fu_778_p1) + $signed(sext_ln60_1_fu_788_p1));

assign addr_cmp41_fu_482_p2 = ((reuse_addr_reg38_fu_130 == zext_ln30_fu_465_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_491_p2 = ((reuse_addr_reg_fu_138 == zext_ln30_fu_465_p1) ? 1'b1 : 1'b0);

assign and_ln53_fu_804_p2 = (icmp_reg_1015_pp0_iter3_reg & icmp_ln53_reg_1057_pp0_iter3_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln29_fu_382_p2 == 1'd0) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (out_stream_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335 = 'bx;

assign ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299 = 'bx;

assign ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308 = 'bx;

assign ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317 = 'bx;

assign ap_phi_reg_pp0_iter0_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326 = 'bx;

assign ap_ready = ap_ready_sig;

assign cmp105_fu_460_p2 = ((zext_ln29_fu_430_p1 == sub104) ? 1'b1 : 1'b0);

assign cmp2139_read_reg_998 = cmp2139;

assign first_iter_0_fu_438_p2 = ((select_ln29_fu_408_p3 == 11'd0) ? 1'b1 : 1'b0);

assign gx_fu_740_p2 = ($signed(add_ln56_fu_734_p2) + $signed(sext_ln56_fu_730_p1));

assign gy_fu_798_p2 = ($signed(add_ln60_fu_792_p2) + $signed(sext_ln60_fu_752_p1));

assign icmp_fu_454_p2 = ((tmp_3_fu_444_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_382_p2 = ((indvar_flatten_fu_154 == mul_ln6) ? 1'b1 : 1'b0);

assign icmp_ln30_1_fu_618_p2 = (($signed(zext_ln30_2_fu_615_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_397_p2 = (($signed(zext_ln30_1_fu_393_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_517_p2 = ((tmp_4_fu_507_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_523_p2 = ((select_ln29_2_cast_fu_434_p1 == sub107) ? 1'b1 : 1'b0);

assign out_pixel_last_fu_528_p2 = (icmp_ln82_fu_523_p2 & cmp105_fu_460_p2);

assign out_stream_TDATA = ((output_pixel_2_fu_877_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign out_stream_TDEST = 'bx;

assign out_stream_TID = 'bx;

assign out_stream_TKEEP = 1'd1;

assign out_stream_TLAST = out_pixel_last_reg_1062_pp0_iter3_reg;

assign out_stream_TSTRB = 1'd1;

assign out_stream_TUSER = curr_pixel_user_reg_1030_pp0_iter3_reg;

assign output_pixel_2_fu_877_p2 = (output_pixel_fu_872_p2 & and_ln53_fu_804_p2);

assign output_pixel_fu_872_p2 = ((sext_ln65_fu_868_p1 > empty) ? 1'b1 : 1'b0);

assign reuse_select42_fu_588_p3 = ((addr_cmp41_reg_1041[0:0] == 1'b1) ? reuse_reg37_fu_134 : sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_q1);

assign reuse_select_fu_598_p3 = ((addr_cmp_reg_1052[0:0] == 1'b1) ? reuse_reg_fu_142 : sobel_accel_stream_stream_axis_0_int_int_int_line_buf_q1);

assign select_ln29_1_fu_422_p3 = ((icmp_ln30_fu_397_p2[0:0] == 1'b1) ? y_fu_150 : add_ln29_1_fu_416_p2);

assign select_ln29_2_cast_fu_434_p1 = select_ln29_fu_408_p3;

assign select_ln29_fu_408_p3 = ((icmp_ln30_fu_397_p2[0:0] == 1'b1) ? x_fu_146 : 11'd0);

assign sext_ln55_fu_808_p1 = gx_reg_1128;

assign sext_ln56_fu_730_p1 = $signed(sub_ln55_fu_724_p2);

assign sext_ln57_fu_700_p1 = $signed(tmp_fu_692_p3);

assign sext_ln59_fu_811_p1 = gy_reg_1135;

assign sext_ln60_1_fu_788_p1 = $signed(sub_ln61_fu_782_p2);

assign sext_ln60_fu_752_p1 = $signed(sub_ln59_fu_746_p2);

assign sext_ln61_fu_778_p1 = $signed(tmp_1_fu_770_p3);

assign sext_ln63_fu_834_p1 = $signed(abs_gx_fu_827_p3);

assign sext_ln64_fu_858_p1 = $signed(abs_gy_fu_851_p3);

assign sext_ln65_fu_868_p1 = $signed(sum_mag_fu_862_p2);

assign sobel_accel_stream_stream_axis_0_int_int_int_line_buf_1_address1 = zext_ln30_fu_465_p1;

assign sobel_accel_stream_stream_axis_0_int_int_int_line_buf_address1 = zext_ln30_fu_465_p1;

assign sub_ln55_fu_724_p2 = (zext_ln57_1_fu_707_p1 - zext_ln55_2_fu_720_p1);

assign sub_ln56_fu_686_p2 = (zext_ln56_1_fu_679_p1 - zext_ln56_2_fu_682_p1);

assign sub_ln59_fu_746_p2 = (zext_ln57_2_fu_710_p1 - zext_ln56_fu_675_p1);

assign sub_ln60_fu_764_p2 = (zext_ln60_fu_756_p1 - zext_ln60_1_fu_760_p1);

assign sub_ln61_fu_782_p2 = (zext_ln57_fu_704_p1 - zext_ln55_1_fu_672_p1);

assign sub_ln63_fu_822_p2 = ($signed(11'd0) - $signed(gx_reg_1128));

assign sub_ln64_fu_846_p2 = ($signed(11'd0) - $signed(gy_reg_1135));

assign sum_mag_fu_862_p2 = ($signed(sext_ln63_fu_834_p1) + $signed(sext_ln64_fu_858_p1));

assign tmp_1_fu_770_p3 = {{sub_ln60_fu_764_p2}, {1'd0}};

assign tmp_3_fu_444_p4 = {{select_ln29_1_fu_422_p3[30:1]}};

assign tmp_4_fu_507_p4 = {{select_ln29_fu_408_p3[10:1]}};

assign tmp_5_fu_814_p3 = sext_ln55_fu_808_p1[32'd15];

assign tmp_6_fu_838_p3 = sext_ln59_fu_811_p1[32'd15];

assign tmp_fu_692_p3 = {{sub_ln56_fu_686_p2}, {1'd0}};

assign zext_ln29_fu_430_p1 = select_ln29_1_fu_422_p3;

assign zext_ln30_1_fu_393_p1 = x_fu_146;

assign zext_ln30_2_fu_615_p1 = add_ln30_reg_1067;

assign zext_ln30_fu_465_p1 = select_ln29_fu_408_p3;

assign zext_ln55_1_fu_672_p1 = reuse_select42_reg_1114;

assign zext_ln55_2_fu_720_p1 = add_ln57_fu_714_p2;

assign zext_ln55_fu_669_p1 = reuse_select42_reg_1114;

assign zext_ln56_1_fu_679_p1 = reuse_select_reg_1120;

assign zext_ln56_2_fu_682_p1 = ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_8_reg_317;

assign zext_ln56_fu_675_p1 = ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_6_reg_299;

assign zext_ln57_1_fu_707_p1 = curr_pixel_data_reg_1020_pp0_iter2_reg;

assign zext_ln57_2_fu_710_p1 = ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_9_reg_326;

assign zext_ln57_fu_704_p1 = curr_pixel_data_reg_1020_pp0_iter2_reg;

assign zext_ln60_1_fu_760_p1 = ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_7_reg_308;

assign zext_ln60_fu_756_p1 = ap_phi_reg_pp0_iter3_p_ZZ11sobel_accelRN3hls6streamINS_4axisI7ap_uintILi8EELm1ELm1ELm1ELh56ELb0EEELi0E_10_reg_335;

endmodule //sobel_accel_sobel_accel_Pipeline_ROW_LOOP_COL_LOOP
